task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_PR == ''
  container:
    dockerfile: .ci/Dockerfile
    cpu: 8
    memory: 16G
  pub_cache:
    folder: ~/.pub-cache
  setup_script:
    - pod repo update
    - flutter channel stable
    - flutter upgrade
  test_script: flutter test
  build_script: 
    - cd example
    - flutter build apk

task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  osx_instance:
    image: mojave-xcode-10.2-flutter
  pub_cache:
    folder: ~/.pub-cache
  setup_script:
    - pod repo update
    - flutter channel stable
    - flutter upgrade
  create_simulator_script:
    - xcrun simctl list
    - xcrun simctl create Flutter-iPhone com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-12-2 | xargs xcrun simctl boot
    test_script: flutter test
    build_script: 
      - cd example
      - flutter build ios --no-codesign
